const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const memory=new Map();let uid='one';let available=[];
const window={firebase:{auth:()=>({currentUser:{uid}})},addEventListener(){},speechSynthesis:{getVoices:()=>available}};
const context={window,document:{addEventListener(){}},localStorage:{getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)}};
vm.runInNewContext(readFileSync(__dirname+'/../assistant-settings.js','utf8'),context);
const a=window.AssistantSettings;
const save=x=>memory.set('smarthub:assistant:v1:'+uid,JSON.stringify(x));
assert.equal(a.name(),'María');assert(a.invoked('María, abre portón'));assert(!a.invoked('mariano abre portón'));
save({name:'Tomás',profile:'male',voices:{}});
assert(a.invoked('hola tomas, abre portón'));assert(!a.invoked('María abre portón'));assert(!a.invoked('tomases'));
assert.equal(a.strip('Tomás, abre portón'),', abre porton');
assert.equal(a.display('María · escuchando'),'Tomás · escuchando');
uid='two';assert.equal(a.name(),'María');uid='one';assert.equal(a.name(),'Tomás');
available=[{name:'Monica',lang:'es-ES',voiceURI:'es'},{name:'Paulina',lang:'es-MX',voiceURI:'mx'},{name:'Rodrigo',lang:'es-CL',voiceURI:'cl'}];
let u={};a.apply(u);assert.equal(u.voice.voiceURI,'cl');assert.equal(u.pitch,1);
u={};a.apply(u,{profile:'female',voices:{}});assert.equal(u.voice.voiceURI,'mx');
u={};a.apply(u,{profile:'female',voices:{female:'es'}});assert.equal(u.voice.voiceURI,'es');
available=[];u={};a.apply(u);assert.equal(u.lang,'es-CL');
context.localStorage.getItem=()=>{throw Error('denied')};assert.equal(a.name(),'María');
console.log('PASS: custom wake name, accents, word boundaries, account isolation, voice preference, Latin American ranking, empty voices and blocked storage. No device commands sent.');
